theme: jekyll-theme-hacker
title: Cavalon's Notes
show_downloads: true
description: [Collection of my notes]
google_analytics:
resume:
  title: Resume PDF
  url: http://www.africau.edu/images/default/sample.pdf